/** All player-facing copy for the template, kept in one place for localisation. */
export const STRINGS = {
  peekHint: 'Hold to peek',
  peekHintHeld: 'Release to put them down',
  muckHint: 'Swipe up to fold',
  checkHint: 'Double-tap felt to check',
  callHint: 'Tap chips to call',
  raiseHint: 'Drag chips to raise',
  folded: 'Mucked',
  checked: 'Check',
  called: 'Call',
  raised: 'Raise',
  nextHand: 'Deal next hand',
  chooseCards: 'Set cards',
  cardPickerTitle: 'Which cards does the player peek?',
  cardPickerRandom: 'Random hand',
  cardPickerApply: 'Deal this hand',
  cardPickerClose: 'Close',
  skinLabel: 'Table',
  potLabel: 'Pot',
} as const;
