export const EQUITY_STRINGS = {
  title: 'THE EQUITY SCALE',
  stage1Instruction: 'Turn the dial to the number of outs, then lock it in.',
  stage2Instruction: 'Dial the equity, then lock in Call or Fold.',
  outsDialLabel: 'Outs dial',
  equityDialLabel: 'Equity dial',
  potLabel: 'Total pot',
  callLabel: 'Price to call',
  oddsLabel: 'Pot odds',
  lockIn: 'LOCK IN',
  fold: 'FOLD',
  call: 'CALL',
  outsUnit: 'OUTS',
  equityUnit: 'EQ%',
  lockedOuts: 'Locked outs',
  submitting: 'Checking the price…',
  stampOuts: 'OUTS',
  stampEquity: 'EQUITY',
  stampDecision: 'DECISION',
  revealPerfect: '3/3 — jackpot math.',
  revealClose: '2/3 — the decision still paid.',
  revealMiss: 'The price tipped against that line.',
} as const;
