// Generated by scripts/cut-scale-rig.py. Canvas px in the 1197x998 padded space.
export const SCALE_RIG_LAYERS = {
  body: { x: 372, y: 156, w: 450, h: 688 },
  hoseLeft: { x: 69, y: 154, w: 418, h: 364 },
  hoseRight: { x: 719, y: 156, w: 410, h: 353 },
  panLeft: { x: 68, y: 370, w: 245, h: 329 },
  panRight: { x: 884, y: 378, w: 240, h: 299 },
} as const;
export const SCALE_RIG_PIVOTS = {
  left: { x: 465, y: 448 },
  right: { x: 731, y: 434 },
} as const;
export const SCALE_RIG_RINGS = {
  left: { x: 210.8, y: 379.1 },
  right: { x: 985.7, y: 367.2 },
} as const;
