export {
  advanceStep,
  allowedActionsForStep,
  currentStep,
  isComplete,
  matchesCurrentStep,
  stepFromAction,
} from './stepMachine';
export { EQUITY_SCALE_TUTORIAL, EQUITY_SCALE_TUTORIAL_ID } from './equityScaleSteps';
export { PEEK_AND_PITCH_TUTORIAL, PEEK_AND_PITCH_TUTORIAL_ID } from './peekAndPitchSteps';
export { hasSeenTemplateTutorial, markTemplateTutorialSeen, tutorialSeenKey } from './tutorialAck';
export {
  glovePoseDeg,
  heldTravelProgress,
  horizonHeadingForDial,
  horizonHeadingForSwipe,
  pairTapProgress,
  rightHandEdgeLift,
  rotateTravelDirection,
  rotateTravelProgress,
  visualMotionForHand,
} from './visualMotion';
export type { GestureVisualMotion } from './visualMotion';
export {
  approxQuadLength,
  buildTearDropOutline,
  cometDashOffset,
  cometTailLength,
  dialArcLength,
  dialRotatePath,
  fingerPathForStep,
  fallbackTableRects,
  overlayViewport,
  POINTING_GLOVE_H,
  POINTING_GLOVE_TIP_X,
  POINTING_GLOVE_TIP_Y,
  POINTING_GLOVE_W,
  pointingGloveFrame,
  pointOnArc,
  pointOnQuad,
  rectCenter,
  rectsOverlap,
  sampleTrailCenterline,
  smoothClosedOutline,
  spotlightForTarget,
  quadPathD,
  swipeArcForAction,
  tapOriginForAction,
  tapOriginForTarget,
  tangentOnDialArc,
  tangentOnQuad,
  tutorialCopyTop,
  warmthTrailProfile,
  outlineToSvgPathD,
  CONTACT_GLOW_RADIUS,
} from './tutorialGeometry';
export type {
  TrailCenterlineInput,
  TutorialArc,
  TutorialControlHits,
  TutorialDialArc,
  TutorialPoint,
  TutorialRect,
  TutorialSpotlight,
  WarmthTrailHeatStop,
  WarmthTrailProfile,
  WarmthTrailSize,
} from './tutorialGeometry';
export type {
  GestureTutorialAction,
  GestureTutorialConfig,
  GestureTutorialHand,
  GestureTutorialStep,
  GestureTutorialTarget,
} from './types';
