name: EAS Update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: my-expo-app/package-lock.json

      - name: Install eas-cli
        run: npm install -g eas-cli

      - name: Install dependencies
        working-directory: my-expo-app
        run: npm install

      - name: Publish update
        working-directory: my-expo-app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          CI: 1
        run: eas update --auto --non-interactive